유저 학교인증 요청
School-Mate/School-Mate-Backend pull request #15
Opened 2023-07-07 09:50 UTC by KIMTAEKJUN

2023-07-08 04:27 UTC, ombe1229 requested changes

2023-07-08 04:27 UTC, ombe1229 commented on src/dtos/school.dto.ts
> +  @IsString({ message: '' })
```suggestion
  @IsString({ message: '이미지 아이디를 입력해주세요,' })
```

2023-07-09 04:53 UTC, kiss8981 requested changes

2023-07-09 04:53 UTC, kiss8981 commented on src/services/school.service.ts
> +      console.log(error);
테스트 코드 삭제

2023-07-09 04:53 UTC, kiss8981 commented on src/services/school.service.ts
> +          process: 'pending',
생성된 Enum 사용

2023-07-09 05:25 UTC, merged